spring.application.name=tienda
server.port=8081

#clase 2
#para definir el formato de despliegue de fecha/hora del log
logging.pattern.dateformat=hh:mm
#para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off
#en el desarrollo el "cache' del servidor (false), en produccion "true"
spring.thymeleaf.cache=false
