#clase1
spring.application.name=tienda
server.port=8081

#clase 2
#para definir el formato de despliegue de fecha/hora del log
logging.pattern.dateformat=hh:mm
#para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off
#en el desarrollo el "cache' del servidor (false), en produccion "true"
spring.thymeleaf.cache=false
#Clase 3
#Conexión local a la BD Techshop en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/techshop
#spring.datasource.url=jdbc:mysql://mysql-5763.l.aivencloud.com:16441/techshop
#spring.datasource.url=url=jdbc:mysql://techshop-desarrolloaplicacionescurso-5763.l.aivencloud.com:16441/techshop
#Usuario y clave de creaTablas.sql
spring.datasource.username=root
spring.datasource.password=Fidelitas.25

#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE
#clase 4
#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=techshop-7431b.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-7431b-firebase-adminsdk-fbsvc-1db30dd7c3.json

#Propiedades para enviar correos--
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=desarrolloaplicacionescurso@gmail.com
spring.mail.password=wkcyfqtnoxlsymlh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#nombre del servidor donde esta la tienda
servidor.http=localhost